name: Build Agents Action
description: Build country's agents into a docker image

inputs:
  country:
    required: true
    description: Country's agents
  dockerRegistryPassword:
    required: true
    description: Docker registry credentials
  dockerRegistry:
    required: false
    description: docker registry host
    default: ghcr.io
  dockerImageOwner:
    required: false
    description: Owner of image
    default: filmcalendar
  dockerImageName:
    required: false
    description: Image's name
    default: fc-agents

runs:
  using: composite
  steps:
    - run: |
        cp ${{ github.action_path }}/Dockerfile . |
        cp ${{ github.action_path }}/.dockerignore . |
        cp ${{ github.action_path }}/fc-agents-init.sh .
      shell: bash
    - id: vars
      run: |
        echo ::set-output name=dockerImage::${{ inputs.dockerRegistry }}/${{ inputs.dockerImageOwner }}/${{ inputs.dockerImageName }}-${{ inputs.country }}:latest
      shell: bash
    - run: docker build --tag ${{ steps.vars.outputs.dockerImage }} .
      shell: bash
    - run: echo ${{ inputs.dockerRegistryPassword }} | docker login ${{inputs.dockerRegistry }} --username ${{ github.actor }} --password-stdin
      shell: bash
    - run: docker push ${{ steps.vars.outputs.dockerImage }}
      shell: bash
