name: Build Agents Action
description: Build country's agents into a docker image

inputs:
  fc-country:
    required: true
    description: Country's agents
  docker-registry-password:
    required: true
    description: Docker registry credentials
  docker-registry:
    required: false
    description: docker registry host
    default: ghcr.io
  docker-image-owner:
    required: false
    description: Owner of image
    default: filmcalendar
  docker-image-name:
    required: false
    description: Image's name
    default: fc-agents

runs:
  using: composite
  steps:
    - run: |
        cp ${{ github.action_path }}/Dockerfile . |
        cp ${{ github.action_path }}/.dockerignore . |
        cp ${{ github.action_path }}/fc-agents-init.sh .
      shell: bash
    - id: vars
      run: |
        echo ::set-output name=docker_image::${{ inputs.docker-registry }}/${{ inputs.docker-image-owner }}/${{ inputs.docker-image-name }}-${{ inputs.fc-country }}:latest
      shell: bash
    - run: docker build --tag ${{ steps.vars.outputs.docker_image }} .
      shell: bash
    - run: echo ${{ inputs.docker-registry-password }} | docker login ${{inputs.docker-registry }} --username ${{ github.actor }} --password-stdin
      shell: bash
    - run: docker push ${{ steps.vars.outputs.docker_image }}
      shell: bash
