name: Build Agents Action
description: Build country's agents into a docker image
inputs:
  fc-country:
    required: true
    description: Country's agents
  github-token:
    required: true
    description: GH credentials
runs:
  using: composite
  steps:
    - run: |
        cp ${{ github.action_path }}/Dockerfile . |
        cp ${{ github.action_path }}/.dockerignore .
      shell: bash
    - id: vars
      run: |
        echo ::set-output name=docker_image::ghcr.io/$GITHUB_REPOSITORY/fc-agents-${{ inputs.fc-country }}
      shell: bash
    - run: docker build --build-arg FC_COUNTRY="${{ inputs.fc-country }}" --tag ${{ steps.vars.outputs.docker_image }} .
      shell: bash
    - run: echo ${{ inputs.github-token }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      shell: bash
    - run: docker push ${{ steps.vars.outputs.docker_image }}
      shell: bash
