name: Build Agents Action
description: Build country's agents into a docker image

inputs:
  country:
    required: true
    description: Country's agents

runs:
  using: composite
  steps:
    - run: |
        cp ${{ github.action_path }}/Dockerfile . |
        cp ${{ github.action_path }}/.dockerignore . |
        cp ${{ github.action_path }}/fc-agents-init.sh .
        docker build --tag ghcr.io/filmcalendar/fc-agents-${{ inputs.country }}:latest . |
        echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin |
        docker push ghcr.io/filmcalendar/fc-agents-${{ inputs.country }}:latest |
      shell: bash
