name: Build Agents Action
description: Build country's agents into a docker image
inputs:
  fc-country:
    required: true
    description: Country's agents
runs:
  using: composite
  steps:
    - run: ./docker-build.sh
      shell: bash
      env:
        FC_COUNTRY: ${{ inputs.fc-country }}
